---
name: module3_task0
on:
  schedule:
    - cron: "* 0 * * 0-6"
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Test help command
        run: make help -C module3_task0/
...
